### ISSUE TITLE
ActionHistory

### ISSUE THREAD

**Issue by ft0220** [RCRS-ADF/RCRS-ADF#2]
世界大会で話していた各エージェントの行動履歴をとれる機能はいつ頃実装される予定でしょうか？

**Comment by tkmnet** [comment]
来週実装します

**Comment by tkmnet** [comment]
来週のアップデートに組み込めるものは組み込むので，要望があったらお願いします．

**Comment by ft0220** [comment]
worldInfoなどで燃えている建物や埋まっている人の数が取ってこれると嬉しいです

**Comment by tkmnet** [comment]
すみません．予定を変更させてください．アップデートのコミットは８月の前半にまとめて行います．
