### ISSUE TITLE
install-roborescue ant issue

### ISSUE THREAD

**Issue by mhrimaz** [RCRS-ADF/RCRS-ADF#3]
The ant version in the install-roborescue.sh file is apache-ant-1.10.0 which does not exist in the provided repository http://ftp.riken.jp/net/apache//ant/binaries/
In order to install it without any error you should change ANTVER from

> ANTVER='apache-ant-1.10.0'

to

> ANTVER='apache-ant-1.10.1'

**Comment by tkmnet** [comment]
Thank you for your report.
I improved the script so that able to obtain the version automatically.
